name: Package

permissions:
  contents: write

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Install Checkout
        uses: actions/checkout@v1
      
      - name: Install Setup SP
        uses: rumblefrog/setup-sp@master
        with:
          version: '1.11.x'
      
      - name: Get GitHub Env
        run: |
          echo "PLUGIN_VERSION_REVISION<<EOF" >> $GITHUB_ENV
          git rev-list --count HEAD >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Install Misc
        run: |
          mkdir -p addons/sourcemod/scripting/include
          cd addons/sourcemod/scripting/include
          wget "https://raw.githubusercontent.com/FlaminSarge/tf2attributes/master/scripting/include/tf2attributes.inc"
          wget "https://raw.githubusercontent.com/nosoop/SMExt-TF2Items/main/pawn/tf2items.inc"
        working-directory: ./
      
      - name: Compile
        run: spcomp -E -O2 -v2 -i "include" -o "tf2_custom_taunts" tf2_custom_taunts.sp
        working-directory: addons/sourcemod/scripting
      
      - name: Release
        uses: softprops/action-gh-release@master
        with:
          tag_name: ${{env.PLUGIN_VERSION}}.${{env.PLUGIN_VERSION_REVISION}}
          files: |
            addons/sourcemod/scripting/tf2_custom_taunts.smx
            addons/sourcemod/gamedata/tf2.tauntem.txt
            addons/sourcemod/configs/custom_taunts/taunts.cfg